FROM maven:3.6.3-openjdk-11

WORKDIR /usr/bin/primitive-hamcrest
RUN git clone https://github.com/spideruci/primitive-hamcrest.git .
RUN mvn install -DskipITs -Dmaven.test.skip=true

WORKDIR /usr/bin/tacoco
RUN git clone https://github.com/spideruci/tacoco.git .
RUN mvn install -DskipITs -Dmaven.test.skip=true

WORKDIR /usr/bin/
COPY ./.tox/dist/spidertools-*.zip ./spidertools.zip
RUN unzip spidertools.zip && rm spidertools.zip
RUN 